export interface Scheme {
  id: string;
  name: string;
  nameHi: string;
  description: string;
  descriptionHi: string;
  category: string[];
  ageMin?: number;
  ageMax?: number;
  incomeMax?: number;
  gender?: "male" | "female" | "all";
  states: string[];
  occupations: string[];
  educationLevels?: string[];
  disabilityEligible?: boolean;
  documents: string[];
  documentsHi: string[];
  applyLink: string;
  deadline: string;
  ministry: string;
  ministryHi: string;
}

export const schemes: Scheme[] = [
  {
    id: "pm-kisan",
    name: "PM Kisan Samman Nidhi",
    nameHi: "पीएम किसान सम्मान निधि",
    description: "Financial benefit of ₹6,000 per year to small and marginal farmer families with cultivable land.",
    descriptionHi: "खेती योग्य भूमि वाले छोटे और सीमांत किसान परिवारों को ₹6,000 प्रति वर्ष की वित्तीय सहायता।",
    category: ["farmer"],
    ageMin: 18,
    incomeMax: 200000,
    gender: "all",
    states: ["all"],
    occupations: ["farmer"],
    documents: ["Aadhar Card", "Land Documents", "Bank Account Details"],
    documentsHi: ["आधार कार्ड", "भूमि दस्तावेज़", "बैंक खाता विवरण"],
    applyLink: "https://pmkisan.gov.in",
    deadline: "31 Dec 2025",
    ministry: "Ministry of Agriculture",
    ministryHi: "कृषि मंत्रालय",
  },
  {
    id: "pm-scholarship",
    name: "PM Scholarship Scheme",
    nameHi: "पीएम छात्रवृत्ति योजना",
    description: "Scholarship for students of ex-servicemen and ex-coast guard personnel for professional degree courses.",
    descriptionHi: "पूर्व सैनिकों और पूर्व तटरक्षक कर्मियों के छात्रों के लिए व्यावसायिक डिग्री पाठ्यक्रमों हेतु छात्रवृत्ति।",
    category: ["student"],
    ageMin: 18,
    ageMax: 25,
    incomeMax: 500000,
    gender: "all",
    states: ["all"],
    occupations: ["student"],
    educationLevels: ["higher_secondary", "graduate", "post_graduate"],
    documents: ["Aadhar Card", "Mark Sheets", "Ex-serviceman Certificate", "Bank Account"],
    documentsHi: ["आधार कार्ड", "अंक पत्र", "पूर्व सैनिक प्रमाणपत्र", "बैंक खाता"],
    applyLink: "https://scholarships.gov.in",
    deadline: "31 Oct 2025",
    ministry: "Ministry of Defence",
    ministryHi: "रक्षा मंत्रालय",
  },
  {
    id: "mudra-loan",
    name: "Pradhan Mantri MUDRA Yojana",
    nameHi: "प्रधानमंत्री मुद्रा योजना",
    description: "Loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises for business growth.",
    descriptionHi: "व्यापार वृद्धि के लिए गैर-कॉर्पोरेट, गैर-कृषि लघु/सूक्ष्म उद्यमों को ₹10 लाख तक का ऋण।",
    category: ["entrepreneur"],
    ageMin: 18,
    gender: "all",
    states: ["all"],
    occupations: ["entrepreneur", "self_employed"],
    documents: ["Aadhar Card", "Business Plan", "PAN Card", "Address Proof"],
    documentsHi: ["आधार कार्ड", "व्यापार योजना", "पैन कार्ड", "पते का प्रमाण"],
    applyLink: "https://www.mudra.org.in",
    deadline: "Ongoing",
    ministry: "Ministry of Finance",
    ministryHi: "वित्त मंत्रालय",
  },
  {
    id: "crop-insurance",
    name: "Pradhan Mantri Fasal Bima Yojana",
    nameHi: "प्रधानमंत्री फसल बीमा योजना",
    description: "Crop insurance scheme providing financial support to farmers suffering crop loss due to natural calamities.",
    descriptionHi: "प्राकृतिक आपदाओं से फसल हानि झेलने वाले किसानों को वित्तीय सहायता प्रदान करने वाली फसल बीमा योजना।",
    category: ["farmer"],
    ageMin: 18,
    gender: "all",
    states: ["all"],
    occupations: ["farmer"],
    documents: ["Aadhar Card", "Land Records", "Bank Account", "Sowing Certificate"],
    documentsHi: ["आधार कार्ड", "भूमि अभिलेख", "बैंक खाता", "बुवाई प्रमाणपत्र"],
    applyLink: "https://pmfby.gov.in",
    deadline: "Seasonal",
    ministry: "Ministry of Agriculture",
    ministryHi: "कृषि मंत्रालय",
  },
  {
    id: "ayushman-bharat",
    name: "Ayushman Bharat - PMJAY",
    nameHi: "आयुष्मान भारत - पीएमजेएवाई",
    description: "Health insurance of ₹5 lakh per family per year for secondary and tertiary care hospitalization.",
    descriptionHi: "द्वितीयक और तृतीयक देखभाल अस्पताल में भर्ती के लिए प्रति परिवार प्रति वर्ष ₹5 लाख का स्वास्थ्य बीमा।",
    category: ["general", "farmer", "worker"],
    ageMin: 0,
    incomeMax: 300000,
    gender: "all",
    states: ["all"],
    occupations: ["farmer", "worker", "self_employed", "unemployed"],
    documents: ["Aadhar Card", "Ration Card", "Income Certificate"],
    documentsHi: ["आधार कार्ड", "राशन कार्ड", "आय प्रमाणपत्र"],
    applyLink: "https://pmjay.gov.in",
    deadline: "Ongoing",
    ministry: "Ministry of Health",
    ministryHi: "स्वास्थ्य मंत्रालय",
  },
  {
    id: "sukanya-samriddhi",
    name: "Sukanya Samriddhi Yojana",
    nameHi: "सुकन्या समृद्धि योजना",
    description: "Savings scheme for girl child with high interest rate and tax benefits. For girls below 10 years.",
    descriptionHi: "बालिका के लिए उच्च ब्याज दर और कर लाभ के साथ बचत योजना। 10 वर्ष से कम उम्र की बालिकाओं के लिए।",
    category: ["general"],
    ageMax: 10,
    gender: "female",
    states: ["all"],
    occupations: ["student", "unemployed"],
    documents: ["Birth Certificate", "Aadhar Card of Parent", "Address Proof"],
    documentsHi: ["जन्म प्रमाणपत्र", "अभिभावक का आधार कार्ड", "पते का प्रमाण"],
    applyLink: "https://www.india.gov.in/sukanya-samriddhi-yojana",
    deadline: "Ongoing",
    ministry: "Ministry of Finance",
    ministryHi: "वित्त मंत्रालय",
  },
  {
    id: "startup-india",
    name: "Startup India Scheme",
    nameHi: "स्टार्टअप इंडिया योजना",
    description: "Tax benefits, funding support and mentorship for eligible startups. Simplified compliance and IPR support.",
    descriptionHi: "पात्र स्टार्टअप के लिए कर लाभ, फंडिंग सहायता और मेंटरशिप। सरलीकृत अनुपालन और आईपीआर सहायता।",
    category: ["entrepreneur"],
    ageMin: 18,
    ageMax: 50,
    gender: "all",
    states: ["all"],
    occupations: ["entrepreneur", "self_employed"],
    educationLevels: ["graduate", "post_graduate"],
    documents: ["PAN Card", "Business Registration", "Aadhar Card", "Business Plan"],
    documentsHi: ["पैन कार्ड", "व्यापार पंजीकरण", "आधार कार्ड", "व्यापार योजना"],
    applyLink: "https://www.startupindia.gov.in",
    deadline: "Ongoing",
    ministry: "Ministry of Commerce",
    ministryHi: "वाणिज्य मंत्रालय",
  },
  {
    id: "skill-india",
    name: "Skill India Mission",
    nameHi: "स्किल इंडिया मिशन",
    description: "Free skill development training in various sectors with certification and placement assistance.",
    descriptionHi: "प्रमाणन और प्लेसमेंट सहायता के साथ विभिन्न क्षेत्रों में मुफ्त कौशल विकास प्रशिक्षण।",
    category: ["student", "worker"],
    ageMin: 15,
    ageMax: 45,
    gender: "all",
    states: ["all"],
    occupations: ["student", "worker", "unemployed"],
    educationLevels: ["primary", "secondary", "higher_secondary"],
    documents: ["Aadhar Card", "Education Certificate", "Bank Account"],
    documentsHi: ["आधार कार्ड", "शिक्षा प्रमाणपत्र", "बैंक खाता"],
    applyLink: "https://www.skillindia.gov.in",
    deadline: "Ongoing",
    ministry: "Ministry of Skill Development",
    ministryHi: "कौशल विकास मंत्रालय",
  },
  {
    id: "pm-awas",
    name: "Pradhan Mantri Awas Yojana",
    nameHi: "प्रधानमंत्री आवास योजना",
    description: "Affordable housing for urban and rural poor with interest subsidy on home loans.",
    descriptionHi: "शहरी और ग्रामीण गरीबों के लिए गृह ऋण पर ब्याज सब्सिडी के साथ किफायती आवास।",
    category: ["general", "worker"],
    ageMin: 21,
    incomeMax: 600000,
    gender: "all",
    states: ["all"],
    occupations: ["farmer", "worker", "self_employed"],
    documents: ["Aadhar Card", "Income Certificate", "No Property Certificate", "Bank Account"],
    documentsHi: ["आधार कार्ड", "आय प्रमाणपत्र", "कोई संपत्ति नहीं प्रमाणपत्र", "बैंक खाता"],
    applyLink: "https://pmaymis.gov.in",
    deadline: "31 Mar 2026",
    ministry: "Ministry of Housing",
    ministryHi: "आवास मंत्रालय",
  },
  {
    id: "irrigation-subsidy",
    name: "Pradhan Mantri Krishi Sinchayee Yojana",
    nameHi: "प्रधानमंत्री कृषि सिंचाई योजना",
    description: "Subsidy for micro irrigation systems like drip and sprinkler to improve water use efficiency.",
    descriptionHi: "जल उपयोग दक्षता में सुधार के लिए ड्रिप और स्प्रिंकलर जैसी सूक्ष्म सिंचाई प्रणालियों पर सब्सिडी।",
    category: ["farmer"],
    ageMin: 18,
    gender: "all",
    states: ["all"],
    occupations: ["farmer"],
    documents: ["Aadhar Card", "Land Documents", "Bank Account", "Caste Certificate"],
    documentsHi: ["आधार कार्ड", "भूमि दस्तावेज़", "बैंक खाता", "जाति प्रमाणपत्र"],
    applyLink: "https://pmksy.gov.in",
    deadline: "Ongoing",
    ministry: "Ministry of Agriculture",
    ministryHi: "कृषि मंत्रालय",
  },
  {
    id: "equipment-subsidy",
    name: "Sub-Mission on Agricultural Mechanization",
    nameHi: "कृषि मशीनीकरण पर उप-मिशन",
    description: "Subsidy on purchase of agricultural machinery and equipment for farm modernization.",
    descriptionHi: "कृषि आधुनिकीकरण के लिए कृषि मशीनरी और उपकरणों की खरीद पर सब्सिडी।",
    category: ["farmer"],
    ageMin: 18,
    gender: "all",
    states: ["all"],
    occupations: ["farmer"],
    documents: ["Aadhar Card", "Land Records", "Bank Account", "Quotation of Equipment"],
    documentsHi: ["आधार कार्ड", "भूमि अभिलेख", "बैंक खाता", "उपकरण का कोटेशन"],
    applyLink: "https://agrimachinery.nic.in",
    deadline: "Ongoing",
    ministry: "Ministry of Agriculture",
    ministryHi: "कृषि मंत्रालय",
  },
  {
    id: "ujjwala",
    name: "Pradhan Mantri Ujjwala Yojana",
    nameHi: "प्रधानमंत्री उज्ज्वला योजना",
    description: "Free LPG connections to women from BPL households for clean cooking fuel.",
    descriptionHi: "स्वच्छ खाना पकाने के ईंधन के लिए बीपीएल परिवारों की महिलाओं को मुफ्त एलपीजी कनेक्शन।",
    category: ["general"],
    ageMin: 18,
    incomeMax: 200000,
    gender: "female",
    states: ["all"],
    occupations: ["farmer", "worker", "self_employed", "unemployed"],
    documents: ["Aadhar Card", "BPL Card", "Bank Account", "Passport Photo"],
    documentsHi: ["आधार कार्ड", "बीपीएल कार्ड", "बैंक खाता", "पासपोर्ट फोटो"],
    applyLink: "https://www.pmujjwalayojana.com",
    deadline: "Ongoing",
    ministry: "Ministry of Petroleum",
    ministryHi: "पेट्रोलियम मंत्रालय",
  },
  {
    id: "stand-up-india",
    name: "Stand Up India Scheme",
    nameHi: "स्टैंड अप इंडिया योजना",
    description: "Bank loans between ₹10 lakh and ₹1 crore to SC/ST and women entrepreneurs for greenfield enterprises.",
    descriptionHi: "ग्रीनफील्ड उद्यमों के लिए अनुसूचित जाति/जनजाति और महिला उद्यमियों को ₹10 लाख से ₹1 करोड़ तक का बैंक ऋण।",
    category: ["entrepreneur"],
    ageMin: 18,
    gender: "all",
    states: ["all"],
    occupations: ["entrepreneur", "self_employed"],
    documents: ["Aadhar Card", "Caste Certificate", "Business Plan", "PAN Card", "IT Returns"],
    documentsHi: ["आधार कार्ड", "जाति प्रमाणपत्र", "व्यापार योजना", "पैन कार्ड", "आईटी रिटर्न"],
    applyLink: "https://www.standupmitra.in",
    deadline: "Ongoing",
    ministry: "Ministry of Finance",
    ministryHi: "वित्त मंत्रालय",
  },
  {
    id: "national-pension",
    name: "Atal Pension Yojana",
    nameHi: "अटल पेंशन योजना",
    description: "Guaranteed minimum pension of ₹1,000 to ₹5,000 per month after 60 years of age.",
    descriptionHi: "60 वर्ष की आयु के बाद ₹1,000 से ₹5,000 प्रति माह की गारंटीकृत न्यूनतम पेंशन।",
    category: ["general", "worker"],
    ageMin: 18,
    ageMax: 40,
    gender: "all",
    states: ["all"],
    occupations: ["farmer", "worker", "self_employed"],
    documents: ["Aadhar Card", "Bank Account", "Mobile Number"],
    documentsHi: ["आधार कार्ड", "बैंक खाता", "मोबाइल नंबर"],
    applyLink: "https://www.npscra.nsdl.co.in/scheme-details.php",
    deadline: "Ongoing",
    ministry: "Ministry of Finance",
    ministryHi: "वित्त मंत्रालय",
  },
  {
    id: "disability-pension",
    name: "Indira Gandhi National Disability Pension",
    nameHi: "इंदिरा गांधी राष्ट्रीय विकलांगता पेंशन",
    description: "Monthly pension for persons with severe disabilities living below the poverty line.",
    descriptionHi: "गरीबी रेखा से नीचे जीवन यापन करने वाले गंभीर विकलांग व्यक्तियों के लिए मासिक पेंशन।",
    category: ["general"],
    ageMin: 18,
    incomeMax: 200000,
    gender: "all",
    states: ["all"],
    occupations: ["farmer", "worker", "self_employed", "unemployed", "student"],
    disabilityEligible: true,
    documents: ["Aadhar Card", "Disability Certificate", "BPL Card", "Bank Account"],
    documentsHi: ["आधार कार्ड", "विकलांगता प्रमाणपत्र", "बीपीएल कार्ड", "बैंक खाता"],
    applyLink: "https://nsap.nic.in",
    deadline: "Ongoing",
    ministry: "Ministry of Rural Development",
    ministryHi: "ग्रामीण विकास मंत्रालय",
  },
];

export const indianStates = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
  "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
  "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal",
  "Delhi", "Jammu & Kashmir", "Ladakh", "Puducherry", "Chandigarh",
];

export const occupationOptions = [
  { value: "farmer", label: "Farmer", labelHi: "किसान" },
  { value: "student", label: "Student", labelHi: "छात्र" },
  { value: "entrepreneur", label: "Entrepreneur", labelHi: "उद्यमी" },
  { value: "worker", label: "Worker/Laborer", labelHi: "श्रमिक/मजदूर" },
  { value: "self_employed", label: "Self Employed", labelHi: "स्वरोजगार" },
  { value: "unemployed", label: "Unemployed", labelHi: "बेरोजगार" },
  { value: "government", label: "Government Employee", labelHi: "सरकारी कर्मचारी" },
  { value: "private", label: "Private Sector", labelHi: "निजी क्षेत्र" },
];

export const educationOptions = [
  { value: "none", label: "No Formal Education", labelHi: "कोई औपचारिक शिक्षा नहीं" },
  { value: "primary", label: "Primary (1-5)", labelHi: "प्राथमिक (1-5)" },
  { value: "secondary", label: "Secondary (6-10)", labelHi: "माध्यमिक (6-10)" },
  { value: "higher_secondary", label: "Higher Secondary (11-12)", labelHi: "उच्च माध्यमिक (11-12)" },
  { value: "graduate", label: "Graduate", labelHi: "स्नातक" },
  { value: "post_graduate", label: "Post Graduate", labelHi: "स्नातकोत्तर" },
];
